SetKeyDelay, -1, -1, Play
Send {Blind}{d}{b}{z}
Sleep 1642
Send {Blind}{m}
Sleep 2
Send {Blind}{x}
Sleep 820
Send {Blind}{a}
Sleep 2
Send {Blind}{c}
Sleep 1642
Send {Blind}{b}
Sleep 2
Send {Blind}{m}
Sleep 820
Send {Blind}{v}
Sleep 2
Send {Blind}{n}{z}
Sleep 1642
Send {Blind}{c}
Sleep 2
Send {Blind}{a}
Sleep 820
Send {Blind}{v}
Sleep 2
Send {Blind}{n}{z}
Sleep 1642
Send {Blind}{b}
Sleep 2
Send {Blind}{m}{x}
Sleep 820
Send {Blind}{e}
Sleep 2
Send {Blind}{q}{d}{a}{b}{z}
Sleep 1642
Send {Blind}{w}
Sleep 2
Send {Blind}{j}{g}{b}{x}
Sleep 820
Send {Blind}{d}
Sleep 2
Send {Blind}{h}{q}{n}{c}
Sleep 1642
Send {Blind}{d}
Sleep 2
Send {Blind}{g}{j}{c}
Sleep 820
Send {Blind}{a}
Sleep 2
Send {Blind}{f}{h}{z}{v}
Sleep 1642
Send {Blind}{a}
Sleep 2
Send {Blind}{d}{g}{z}
Sleep 820
Send {Blind}{a}
Sleep 2
Send {Blind}{f}{h}{z}{v}
Sleep 1642
Send {Blind}{s}
Sleep 2
Send {Blind}{g}{j}{b}{x}
Sleep 820
Send {Blind}{e}
Sleep 2
Send {Blind}{q}{d}{a}{b}{z}
Sleep 1642
Send {Blind}{w}
Sleep 2
Send {Blind}{j}{g}{b}{x}{f}
Sleep 1642
Send {Blind}{d}
Sleep 2
Send {Blind}{h}{q}{n}{c}
Sleep 1642
Send {Blind}{d}
Sleep 2
Send {Blind}{g}{j}{c}{s}
Sleep 1642
Send {Blind}{a}
Sleep 2
Send {Blind}{f}{h}{z}{v}
Sleep 1642
Send {Blind}{a}
Sleep 2
Send {Blind}{d}{g}{z}{d}
Sleep 1642
Send {Blind}{s}
Sleep 2
Send {Blind}{f}{h}{z}{v}
Sleep 1642
Send {Blind}{s}
Sleep 2
Send {Blind}{g}{j}{b}{x}{f}
Sleep 1642
Send {Blind}{q}
Sleep 2
Send {Blind}{d}{z}{b}
Sleep 428
Send {Blind}{a}
Sleep 1214
Send {Blind}{g}
Sleep 2
Send {Blind}{j}{x}
Sleep 428
Send {Blind}{f}
Sleep 394
Send {Blind}{b}
Sleep 820
Send {Blind}{q}
Sleep 2
Send {Blind}{d}{c}
Sleep 820
Send {Blind}{h}
Sleep 2
Send {Blind}{e}{a}
Sleep 820
Send {Blind}{t}
Sleep 2
Send {Blind}{e}
Sleep 820
Send {Blind}{y}
Sleep 2
Send {Blind}{w}{b}
Sleep 820
Send {Blind}{r}
Sleep 2
Send {Blind}{h}{z}
Sleep 428
Send {Blind}{q}
Sleep 394
Send {Blind}{n}
Sleep 820
Send {Blind}{e}
Sleep 2
Send {Blind}{g}{z}{b}
Sleep 428
Send {Blind}{d}
Sleep 394
Send {Blind}{a}
Sleep 820
Send {Blind}{s}
Sleep 2
Send {Blind}{f}{z}
Sleep 820
Send {Blind}{q}
Sleep 2
Send {Blind}{h}{n}
Sleep 820
Send {Blind}{q}
Sleep 2
Send {Blind}{g}{x}
Sleep 409
Send {Blind}{f}
Sleep 2
Send {Blind}{q}{m}
Sleep 17
Send {Blind}{j}
Sleep 803
Send {Blind}{d}
Sleep 2
Send {Blind}{q}{z}
Sleep 17
Send {Blind}{j}
Sleep 394
Send {Blind}{b}
Sleep 17
Send {Blind}{q}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{d}
Sleep 803
Send {Blind}{m}
Sleep 2
Send {Blind}{g}
Sleep 17
Send {Blind}{x}
Sleep 803
Send {Blind}{f}
Sleep 2
Send {Blind}{j}{m}
Sleep 820
Send {Blind}{q}
Sleep 2
Send {Blind}{d}{c}
Sleep 820
Send {Blind}{e}
Sleep 2
Send {Blind}{h}{a}
Sleep 17
Send {Blind}{c}
Sleep 803
Send {Blind}{t}
Sleep 2
Send {Blind}{j}
Sleep 17
Send {Blind}{e}
Sleep 803
Send {Blind}{t}
Sleep 2
Send {Blind}{w}{b}
Sleep 17
Send {Blind}{y}
Sleep 803
Send {Blind}{r}
Sleep 2
Send {Blind}{h}
Sleep 17
Send {Blind}{e}
Sleep 394
Send {Blind}{z}
Sleep 17
Send {Blind}{w}
Sleep 394
Send {Blind}{n}
Sleep 17
Send {Blind}{r}
Sleep 394
Send {Blind}{z}
Sleep 409
Send {Blind}{e}
Sleep 2
Send {Blind}{g}{z}
Sleep 17
Send {Blind}{w}
Sleep 394
Send {Blind}{b}
Sleep 17
Send {Blind}{q}
Sleep 394
Send {Blind}{d}
Sleep 17
Send {Blind}{j}
Sleep 394
Send {Blind}{b}
Sleep 409
Send {Blind}{f}
Sleep 2
Send {Blind}{h}
Sleep 17
Send {Blind}{s}
Sleep 394
Send {Blind}{f}{z}
Sleep 17
Send {Blind}{q}
Sleep 394
Send {Blind}{h}{n}
Sleep 17
Send {Blind}{z}
Sleep 409
Send {Blind}{g}
Sleep 2
Send {Blind}{q}
Sleep 17
Send {Blind}{f}
Sleep 394
Send {Blind}{x}
Sleep 409
Send {Blind}{d}
Sleep 2
Send {Blind}{q}{m}
Sleep 17
Send {Blind}{s}
Sleep 394
Send {Blind}{j}{x}
Sleep 17
Send {Blind}{d}
Sleep 394
Send {Blind}{q}
Sleep 17
Send {Blind}{j}
Sleep 394
Send {Blind}{c}
Sleep 17
Send {Blind}{q}
Sleep 394
Send {Blind}{b}
Sleep 17
Send {Blind}{f}
Sleep 394
Send {Blind}{a}
Sleep 409
Send {Blind}{a}
Sleep 2
Send {Blind}{g}
Sleep 17
Send {Blind}{m}
Sleep 394
Send {Blind}{x}
Sleep 409
Send {Blind}{g}
Sleep 2
Send {Blind}{j}{b}
Sleep 17
Send {Blind}{f}
Sleep 394
Send {Blind}{m}
Sleep 409
Send {Blind}{q}
Sleep 2
Send {Blind}{d}
Sleep 17
Send {Blind}{c}
Sleep 803
Send {Blind}{h}
Sleep 2
Send {Blind}{e}{n}
Sleep 17
Send {Blind}{q}
Sleep 394
Send {Blind}{a}
Sleep 409
Send {Blind}{t}
Sleep 2
Send {Blind}{j}
Sleep 17
Send {Blind}{e}
Sleep 394
Send {Blind}{b}
Sleep 409
Send {Blind}{t}
Sleep 2
Send {Blind}{w}{m}
Sleep 17
Send {Blind}{y}
Sleep 394
Send {Blind}{d}
Sleep 409
Send {Blind}{r}
Sleep 2
Send {Blind}{q}{h}
Sleep 17
Send {Blind}{e}
Sleep 394
Send {Blind}{v}
Sleep 409
Send {Blind}{w}
Sleep 2
Send {Blind}{j}{n}
Sleep 17
Send {Blind}{r}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{g}
Sleep 392
Send {Blind}{z}
Sleep 17
Send {Blind}{q}
Sleep 15
Send {Blind}{e}
Sleep 396
Send {Blind}{b}{j}
Sleep 15
Send {Blind}{w}
Sleep 84
Send {Blind}{h}
Sleep 295
Send {Blind}{q}{a}
Sleep 49
Send {Blind}{g}
Sleep 361
Send {Blind}{j}{d}
Sleep 17
Send {Blind}{f}
Sleep 394
Send {Blind}{h}
Sleep 17
Send {Blind}{d}
Sleep 394
Send {Blind}{g}{x}
Sleep 17
Send {Blind}{s}
Sleep 394
Send {Blind}{f}{n}
Sleep 17
Send {Blind}{q}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{g}
Sleep 394
Send {Blind}{q}
Sleep 17
Send {Blind}{x}
Sleep 411
Send {Blind}{s}
Sleep 394
Send {Blind}{j}{b}
Sleep 17
Send {Blind}{w}
Sleep 394
Send {Blind}{m}
Sleep 17
Send {Blind}{g}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{g}{z}
Sleep 18
Send {Blind}{b}
Sleep 411
Send {Blind}{g}
Sleep 214
Send {Blind}{e}
Sleep 180
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 394
Send {Blind}{g}{d}
Sleep 17
Send {Blind}{w}
Sleep 188
Send {Blind}{g}
Sleep 26
Send {Blind}{b}
Sleep 411
Send {Blind}{e}
Sleep 188
Send {Blind}{g}
Sleep 26
Send {Blind}{r}
Sleep 180
Send {Blind}{g}{m}
Sleep 18
Send {Blind}{e}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{d}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{q}
Sleep 18
Send {Blind}{c}
Sleep 411
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 26
Send {Blind}{n}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{j}{a}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{d}{d}
Sleep 197
Send {Blind}{j}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{c}
Sleep 17
Send {Blind}{d}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{g}
Sleep 197
Send {Blind}{m}
Sleep 214
Send {Blind}{a}
Sleep 205
Send {Blind}{f}
Sleep 188
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{z}
Sleep 222
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 17
Send {Blind}{v}
Sleep 205
Send {Blind}{a}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{a}
Sleep 197
Send {Blind}{g}
Sleep 215
Send {Blind}{c}
Sleep 411
Send {Blind}{b}
Sleep 411
Send {Blind}{a}
Sleep 411
Send {Blind}{a}
Sleep 188
Send {Blind}{f}
Sleep 205
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{a}
Sleep 205
Send {Blind}{f}
Sleep 188
Send {Blind}{n}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{q}
Sleep 215
Send {Blind}{s}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{s}
Sleep 188
Send {Blind}{j}
Sleep 17
Send {Blind}{b}
Sleep 205
Send {Blind}{q}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{z}
Sleep 18
Send {Blind}{b}
Sleep 803
Send {Blind}{g}
Sleep 2
Send {Blind}{e}{a}
Sleep 17
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{q}
Sleep 197
Send {Blind}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 26
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{g}
Sleep 188
Send {Blind}{e}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{g}{m}
Sleep 18
Send {Blind}{e}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{d}
Sleep 197
Send {Blind}{w}
Sleep 215
Send {Blind}{c}
Sleep 411
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 26
Send {Blind}{n}
Sleep 365
Send {Blind}{d}
Sleep 30
Send {Blind}{d}
Sleep 197
Send {Blind}{j}{a}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{d}{d}
Sleep 197
Send {Blind}{j}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{c}
Sleep 17
Send {Blind}{d}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{g}
Sleep 197
Send {Blind}{m}
Sleep 214
Send {Blind}{a}
Sleep 205
Send {Blind}{f}
Sleep 188
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{z}
Sleep 222
Send {Blind}{q}
Sleep 205
Send {Blind}{v}
Sleep 205
Send {Blind}{h}
Sleep 197
Send {Blind}{r}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{e}
Sleep 215
Send {Blind}{g}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{a}
Sleep 411
Send {Blind}{a}
Sleep 214
Send {Blind}{f}
Sleep 180
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{a}
Sleep 205
Send {Blind}{f}
Sleep 188
Send {Blind}{n}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{s}{j}
Sleep 215
Send {Blind}{s}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{q}
Sleep 205
Send {Blind}{b}
Sleep 205
Send {Blind}{w}
Sleep 394
Send {Blind}{m}
Sleep 17
Send {Blind}{q}
Sleep 197
Send {Blind}{t}
Sleep 197
Send {Blind}{z}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{b}
Sleep 17
Send {Blind}{r}
Sleep 197
Send {Blind}{t}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{d}
Sleep 17
Send {Blind}{r}
Sleep 197
Send {Blind}{t}
Sleep 215
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{r}
Sleep 197
Send {Blind}{e}
Sleep 215
Send {Blind}{q}
Sleep 394
Send {Blind}{c}
Sleep 17
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{d}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 215
Send {Blind}{h}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{h}
Sleep 215
Send {Blind}{q}
Sleep 394
Send {Blind}{v}
Sleep 17
Send {Blind}{j}
Sleep 197
Send {Blind}{h}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 215
Send {Blind}{f}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{h}
Sleep 215
Send {Blind}{q}
Sleep 394
Send {Blind}{v}
Sleep 17
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{j}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 215
Send {Blind}{h}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{e}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{r}
Sleep 197
Send {Blind}{w}{s}
Sleep 18
Send {Blind}{t}
Sleep 188
Send {Blind}{e}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{z}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{b}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{d}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{e}
Sleep 197
Send {Blind}{t}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{r}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{q}
Sleep 18
Send {Blind}{q}
Sleep 394
Send {Blind}{h}{c}
Sleep 17
Send {Blind}{w}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{q}
Sleep 197
Send {Blind}{e}{n}
Sleep 18
Send {Blind}{d}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 215
Send {Blind}{h}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{d}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{f}
Sleep 197
Send {Blind}{h}
Sleep 18
Send {Blind}{h}
Sleep 394
Send {Blind}{q}{v}
Sleep 17
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}{n}
Sleep 18
Send {Blind}{d}
Sleep 394
Send {Blind}{g}{a}
Sleep 17
Send {Blind}{s}
Sleep 188
Send {Blind}{f}
Sleep 9
Send {Blind}{d}
Sleep 197
Send {Blind}{g}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{s}{a}
Sleep 197
Send {Blind}{d}{c}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{f}
Sleep 9
Send {Blind}{d}
Sleep 197
Send {Blind}{g}{b}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{h}
Sleep 9
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{a}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}
Sleep 18
Send {Blind}{h}
Sleep 394
Send {Blind}{q}{v}
Sleep 17
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{j}{a}
Sleep 17
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{g}
Sleep 197
Send {Blind}{j}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{b}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{j}{m}
Sleep 18
Send {Blind}{e}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{r}
Sleep 197
Send {Blind}{w}{s}
Sleep 18
Send {Blind}{t}
Sleep 188
Send {Blind}{e}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{z}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{b}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{d}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{e}
Sleep 197
Send {Blind}{t}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{h}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{r}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{q}
Sleep 18
Send {Blind}{q}
Sleep 394
Send {Blind}{h}{c}
Sleep 17
Send {Blind}{w}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{q}
Sleep 197
Send {Blind}{e}{n}
Sleep 18
Send {Blind}{d}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 215
Send {Blind}{h}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{g}{b}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{m}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}
Sleep 18
Send {Blind}{h}
Sleep 394
Send {Blind}{q}{v}
Sleep 17
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}{n}
Sleep 18
Send {Blind}{d}
Sleep 394
Send {Blind}{g}{a}
Sleep 17
Send {Blind}{s}
Sleep 188
Send {Blind}{f}
Sleep 9
Send {Blind}{d}
Sleep 197
Send {Blind}{g}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{f}
Sleep 9
Send {Blind}{a}
Sleep 197
Send {Blind}{d}{c}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{f}
Sleep 9
Send {Blind}{d}
Sleep 197
Send {Blind}{g}{b}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{h}
Sleep 9
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{a}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}
Sleep 18
Send {Blind}{h}
Sleep 394
Send {Blind}{q}{v}
Sleep 17
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{j}{a}
Sleep 17
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{g}
Sleep 197
Send {Blind}{j}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{e}
Sleep 197
Send {Blind}{r}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{t}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{z}
Sleep 18
Send {Blind}{q}
Sleep 394
Send {Blind}{b}
Sleep 17
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{w}
Sleep 394
Send {Blind}{d}
Sleep 17
Send {Blind}{q}
Sleep 197
Send {Blind}{w}
Sleep 215
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{x}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 215
Send {Blind}{h}
Sleep 394
Send {Blind}{c}
Sleep 17
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{a}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{s}
Sleep 197
Send {Blind}{d}
Sleep 215
Send {Blind}{f}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{s}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{h}
Sleep 215
Send {Blind}{q}
Sleep 394
Send {Blind}{v}
Sleep 17
Send {Blind}{j}
Sleep 197
Send {Blind}{h}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 215
Send {Blind}{f}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{h}
Sleep 215
Send {Blind}{q}
Sleep 394
Send {Blind}{v}
Sleep 17
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{j}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{h}
Sleep 197
Send {Blind}{j}
Sleep 215
Send {Blind}{q}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{h}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{z}
Sleep 18
Send {Blind}{b}
Sleep 411
Send {Blind}{a}
Sleep 411
Send {Blind}{d}
Sleep 820
Send {Blind}{x}
Sleep 394
Send {Blind}{b}
Sleep 428
Send {Blind}{m}
Sleep 820
Send {Blind}{c}
Sleep 394
Send {Blind}{n}
Sleep 428
Send {Blind}{a}
Sleep 820
Send {Blind}{b}
Sleep 394
Send {Blind}{m}
Sleep 428
Send {Blind}{d}
Sleep 820
Send {Blind}{z}
Sleep 394
Send {Blind}{v}
Sleep 428
Send {Blind}{n}
Sleep 820
Send {Blind}{c}
Sleep 394
Send {Blind}{b}
Sleep 428
Send {Blind}{a}
Sleep 820
Send {Blind}{x}
Sleep 394
Send {Blind}{n}
Sleep 428
Send {Blind}{a}
Sleep 820
Send {Blind}{x}
Sleep 394
Send {Blind}{b}
Sleep 428
Send {Blind}{m}
Sleep 820
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{b}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{d}
Sleep 34
Send {Blind}{g}
Sleep 394
Send {Blind}{j}{x}
Sleep 17
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{j}{b}
Sleep 18
Send {Blind}{j}
Sleep 394
Send {Blind}{g}{m}
Sleep 34
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 205
Send {Blind}{h}{c}
Sleep 18
Send {Blind}{w}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{e}
Sleep 197
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{q}
Sleep 394
Send {Blind}{h}{a}
Sleep 428
Send {Blind}{h}
Sleep 188
Send {Blind}{e}
Sleep 205
Send {Blind}{q}{b}
Sleep 18
Send {Blind}{w}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{q}{m}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{j}{d}
Sleep 34
Send {Blind}{f}
Sleep 188
Send {Blind}{f}
Sleep 205
Send {Blind}{h}{v}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{f}
Sleep 394
Send {Blind}{h}{a}
Sleep 34
Send {Blind}{d}
Sleep 188
Send {Blind}{d}
Sleep 205
Send {Blind}{g}{c}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{h}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}{b}
Sleep 18
Send {Blind}{q}
Sleep 79
Send {Blind}{d}
Sleep 315
Send {Blind}{g}{a}
Sleep 130
Send {Blind}{f}
Sleep 188
Send {Blind}{h}{g}
Sleep 205
Send {Blind}{j}{v}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{h}
Sleep 197
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{f}
Sleep 394
Send {Blind}{h}{a}
Sleep 17
Send {Blind}{g}
Sleep 214
Send {Blind}{g}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{b}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{j}{m}
Sleep 18
Send {Blind}{j}
Sleep 394
Send {Blind}{g}{s}
Sleep 34
Send {Blind}{q}
Sleep 188
Send {Blind}{e}
Sleep 205
Send {Blind}{q}{b}
Sleep 18
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{e}
Sleep 394
Send {Blind}{q}{d}
Sleep 34
Send {Blind}{w}
Sleep 394
Send {Blind}{j}{b}
Sleep 17
Send {Blind}{e}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{r}
Sleep 197
Send {Blind}{w}{m}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{h}
Sleep 215
Send {Blind}{h}
Sleep 188
Send {Blind}{q}
Sleep 205
Send {Blind}{h}{c}
Sleep 18
Send {Blind}{w}
Sleep 188
Send {Blind}{j}
Sleep 9
Send {Blind}{e}
Sleep 197
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{q}
Sleep 394
Send {Blind}{a}
Sleep 17
Send {Blind}{j}
Sleep 214
Send {Blind}{j}
Sleep 197
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{c}
Sleep 18
Send {Blind}{r}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{e}
Sleep 197
Send {Blind}{j}{b}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{t}
Sleep 197
Send {Blind}{e}{m}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{y}
Sleep 197
Send {Blind}{r}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{y}
Sleep 205
Send {Blind}{r}{v}
Sleep 18
Send {Blind}{t}
Sleep 197
Send {Blind}{r}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{y}
Sleep 394
Send {Blind}{r}{a}
Sleep 17
Send {Blind}{q}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{e}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{e}{c}
Sleep 18
Send {Blind}{r}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{y}
Sleep 205
Send {Blind}{r}
Sleep 18
Send {Blind}{t}
Sleep 197
Send {Blind}{r}
Sleep 197
Send {Blind}{q}{v}
Sleep 18
Send {Blind}{y}
Sleep 188
Send {Blind}{r}
Sleep 9
Send {Blind}{t}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{r}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{y}
Sleep 197
Send {Blind}{r}{a}
Sleep 18
Send {Blind}{w}
Sleep 188
Send {Blind}{u}
Sleep 205
Send {Blind}{t}
Sleep 18
Send {Blind}{y}
Sleep 188
Send {Blind}{r}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{j}{m}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{z}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{b}
Sleep 222
Send {Blind}{g}
Sleep 205
Send {Blind}{g}
Sleep 188
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{q}
Sleep 197
Send {Blind}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 26
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{g}
Sleep 188
Send {Blind}{e}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{g}{m}
Sleep 18
Send {Blind}{e}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{d}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{q}
Sleep 18
Send {Blind}{c}
Sleep 411
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 26
Send {Blind}{n}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{j}{a}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{d}
Sleep 197
Send {Blind}{j}
Sleep 18
Send {Blind}{g}
Sleep 394
Send {Blind}{c}
Sleep 17
Send {Blind}{d}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{g}
Sleep 197
Send {Blind}{m}
Sleep 214
Send {Blind}{a}
Sleep 205
Send {Blind}{f}
Sleep 188
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{z}
Sleep 222
Send {Blind}{a}
Sleep 188
Send {Blind}{g}{j}
Sleep 17
Send {Blind}{v}
Sleep 205
Send {Blind}{a}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{g}
Sleep 223
Send {Blind}{c}
Sleep 411
Send {Blind}{g}
Sleep 188
Send {Blind}{q}
Sleep 26
Send {Blind}{b}
Sleep 197
Send {Blind}{g}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{g}
Sleep 197
Send {Blind}{q}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{f}
Sleep 197
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{a}
Sleep 205
Send {Blind}{f}
Sleep 188
Send {Blind}{n}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{j}
Sleep 215
Send {Blind}{s}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{s}
Sleep 188
Send {Blind}{q}
Sleep 17
Send {Blind}{b}
Sleep 205
Send {Blind}{s}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{e}
Sleep 205
Send {Blind}{z}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{b}
Sleep 222
Send {Blind}{g}
Sleep 205
Send {Blind}{g}
Sleep 188
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{q}
Sleep 197
Send {Blind}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 26
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 214
Send {Blind}{g}
Sleep 188
Send {Blind}{e}
Sleep 17
Send {Blind}{r}
Sleep 188
Send {Blind}{g}{m}
Sleep 18
Send {Blind}{e}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{d}
Sleep 197
Send {Blind}{w}
Sleep 215
Send {Blind}{c}
Sleep 411
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 26
Send {Blind}{n}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{j}{a}
Sleep 186
Send {Blind}{d}
Sleep 21
Send {Blind}{q}
Sleep 185
Send {Blind}{d}
Sleep 39
Send {Blind}{g}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{t}
Sleep 197
Send {Blind}{u}
Sleep 197
Send {Blind}{m}
Sleep 215
Send {Blind}{u}
Sleep 215
Send {Blind}{y}
Sleep 197
Send {Blind}{t}
Sleep 197
Send {Blind}{v}
Sleep 18
Send {Blind}{r}
Sleep 197
Send {Blind}{t}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{r}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{w}
Sleep 197
Send {Blind}{e}
Sleep 215
Send {Blind}{w}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{h}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{h}
Sleep 215
Send {Blind}{g}
Sleep 197
Send {Blind}{f}
Sleep 197
Send {Blind}{v}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{h}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{f}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{j}
Sleep 215
Send {Blind}{h}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{s}
Sleep 18
Send {Blind}{g}
Sleep 197
Send {Blind}{e}
Sleep 197
Send {Blind}{z}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{b}
Sleep 223
Send {Blind}{g}
Sleep 392
Send {Blind}{e}
Sleep 2
Send {Blind}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{j}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{y}
Sleep 205
Send {Blind}{q}{b}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{j}{m}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{s}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{h}
Sleep 205
Send {Blind}{q}{e}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{c}
Sleep 222
Send {Blind}{d}
Sleep 392
Send {Blind}{d}
Sleep 2
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{e}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{c}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{e}
Sleep 205
Send {Blind}{b}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{w}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{f}
Sleep 205
Send {Blind}{h}{q}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{z}
Sleep 222
Send {Blind}{a}
Sleep 392
Send {Blind}{f}
Sleep 2
Send {Blind}{h}{v}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{g}
Sleep 9
Send {Blind}{q}
Sleep 17
Send {Blind}{q}
Sleep 188
Send {Blind}{a}
Sleep 18
Send {Blind}{c}
Sleep 205
Send {Blind}{q}
Sleep 205
Send {Blind}{q}
Sleep 188
Send {Blind}{g}{b}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{g}{a}
Sleep 17
Send {Blind}{q}
Sleep 214
Send {Blind}{a}
Sleep 180
Send {Blind}{h}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{x}
Sleep 222
Send {Blind}{a}
Sleep 392
Send {Blind}{f}
Sleep 2
Send {Blind}{n}
Sleep 18
Send {Blind}{h}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{w}
Sleep 9
Send {Blind}{q}
Sleep 215
Send {Blind}{s}
Sleep 197
Send {Blind}{x}
Sleep 214
Send {Blind}{s}
Sleep 188
Send {Blind}{j}
Sleep 17
Send {Blind}{b}
Sleep 205
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{w}{m}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{q}
Sleep 205
Send {Blind}{e}{z}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{b}
Sleep 222
Send {Blind}{g}
Sleep 392
Send {Blind}{q}
Sleep 2
Send {Blind}{e}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{w}
Sleep 205
Send {Blind}{r}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{j}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{y}
Sleep 205
Send {Blind}{q}{b}
Sleep 18
Send {Blind}{g}
Sleep 373
Send {Blind}{t}
Sleep 21
Send {Blind}{j}{m}
Sleep 17
Send {Blind}{g}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{s}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 205
Send {Blind}{e}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{c}
Sleep 222
Send {Blind}{d}
Sleep 392
Send {Blind}{d}
Sleep 2
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 9
Send {Blind}{w}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{e}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{c}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{e}{b}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{w}
Sleep 205
Send {Blind}{m}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{f}
Sleep 205
Send {Blind}{h}{q}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{z}
Sleep 222
Send {Blind}{a}
Sleep 392
Send {Blind}{a}
Sleep 2
Send {Blind}{h}{v}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{n}
Sleep 18
Send {Blind}{a}
Sleep 188
Send {Blind}{g}
Sleep 9
Send {Blind}{q}
Sleep 17
Send {Blind}{q}
Sleep 206
Send {Blind}{j}
Sleep 188
Send {Blind}{c}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{d}
Sleep 197
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 392
Send {Blind}{h}
Sleep 2
Send {Blind}{f}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{v}
Sleep 18
Send {Blind}{q}
Sleep 392
Send {Blind}{f}
Sleep 2
Send {Blind}{h}{n}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 392
Send {Blind}{s}
Sleep 2
Send {Blind}{j}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{s}
Sleep 205
Send {Blind}{x}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{q}
Sleep 204
Send {Blind}{b}
Sleep 19
Send {Blind}{s}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{e}
Sleep 205
Send {Blind}{z}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{b}
Sleep 222
Send {Blind}{g}
Sleep 392
Send {Blind}{g}
Sleep 2
Send {Blind}{q}{e}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{q}{e}
Sleep 9
Send {Blind}{q}
Sleep 197
Send {Blind}{r}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{j}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{y}
Sleep 205
Send {Blind}{q}{x}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{t}{b}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{h}
Sleep 205
Send {Blind}{r}{m}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 223
Send {Blind}{e}{d}
Sleep 188
Send {Blind}{c}
Sleep 222
Send {Blind}{d}
Sleep 392
Send {Blind}{d}
Sleep 2
Send {Blind}{q}{n}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{d}{w}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{e}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{c}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{h}
Sleep 205
Send {Blind}{e}{b}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{w}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{f}
Sleep 214
Send {Blind}{f}
Sleep 180
Send {Blind}{h}{q}
Sleep 18
Send {Blind}{f}
Sleep 188
Send {Blind}{v}
Sleep 222
Send {Blind}{f}
Sleep 392
Send {Blind}{f}
Sleep 2
Send {Blind}{h}{n}
Sleep 18
Send {Blind}{j}
Sleep 197
Send {Blind}{q}
Sleep 197
Send {Blind}{a}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{g}{q}
Sleep 26
Send {Blind}{q}
Sleep 197
Send {Blind}{j}
Sleep 197
Send {Blind}{c}
Sleep 18
Send {Blind}{q}
Sleep 197
Send {Blind}{g}
Sleep 197
Send {Blind}{d}{b}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 392
Send {Blind}{f}
Sleep 2
Send {Blind}{h}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{v}
Sleep 18
Send {Blind}{q}
Sleep 392
Send {Blind}{f}
Sleep 2
Send {Blind}{h}{n}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 392
Send {Blind}{s}
Sleep 2
Send {Blind}{j}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{s}
Sleep 205
Send {Blind}{x}
Sleep 18
Send {Blind}{s}
Sleep 188
Send {Blind}{q}
Sleep 204
Send {Blind}{b}
Sleep 19
Send {Blind}{s}
Sleep 197
Send {Blind}{w}
Sleep 197
Send {Blind}{m}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{e}
Sleep 205
Send {Blind}{z}
Sleep 18
Send {Blind}{q}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{b}
Sleep 18
Send {Blind}{g}
Sleep 392
Send {Blind}{e}
Sleep 2
Send {Blind}{a}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{r}
Sleep 205
Send {Blind}{d}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{t}
Sleep 205
Send {Blind}{j}
Sleep 18
Send {Blind}{h}
Sleep 188
Send {Blind}{y}
Sleep 205
Send {Blind}{q}{x}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{j}
Sleep 205
Send {Blind}{t}{b}
Sleep 18
Send {Blind}{g}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{j}{r}{m}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 223
Send {Blind}{e}{d}
Sleep 188
Send {Blind}{c}
Sleep 222
Send {Blind}{d}
Sleep 392
Send {Blind}{d}
Sleep 2
Send {Blind}{n}
Sleep 16
Send {Blind}{q}
Sleep 2
Send {Blind}{d}
Sleep 188
Send {Blind}{q}
Sleep 26
Send {Blind}{w}
Sleep 180
Send {Blind}{a}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{g}
Sleep 205
Send {Blind}{e}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{d}
Sleep 205
Send {Blind}{r}{c}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{h}
Sleep 205
Send {Blind}{e}{b}
Sleep 18
Send {Blind}{d}
Sleep 188
Send {Blind}{w}
Sleep 205
Send {Blind}{a}
Sleep 18
Send {Blind}{f}
Sleep 214
Send {Blind}{q}
Sleep 18
Send {Blind}{f}
Sleep 191
Send {Blind}{v}
Sleep 225
Send {Blind}{f}
Sleep 397
Send {Blind}{h}
Sleep 2
Send {Blind}{n}
Sleep 18
Send {Blind}{j}
Sleep 200
Send {Blind}{q}
Sleep 200
Send {Blind}{a}
Sleep 18
Send {Blind}{d}
Sleep 191
Send {Blind}{g}{q}
Sleep 26
Send {Blind}{q}
Sleep 200
Send {Blind}{j}
Sleep 200
Send {Blind}{c}
Sleep 18
Send {Blind}{q}
Sleep 200
Send {Blind}{g}
Sleep 200
Send {Blind}{b}
Sleep 18
Send {Blind}{q}
Sleep 191
Send {Blind}{j}
Sleep 208
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 398
Send {Blind}{f}
Sleep 2
Send {Blind}{h}
Sleep 18
Send {Blind}{q}
Sleep 191
Send {Blind}{j}
Sleep 208
Send {Blind}{v}
Sleep 18
Send {Blind}{q}
Sleep 398
Send {Blind}{f}
Sleep 2
Send {Blind}{h}{n}
Sleep 18
Send {Blind}{q}
Sleep 191
Send {Blind}{j}
Sleep 208
Send {Blind}{a}
Sleep 18
Send {Blind}{q}
Sleep 398
Send {Blind}{s}
Sleep 2
Send {Blind}{j}
Sleep 18
Send {Blind}{g}
Sleep 191
Send {Blind}{s}
Sleep 208
Send {Blind}{x}
Sleep 18
Send {Blind}{q}
Sleep 18
Send {Blind}{s}
Sleep 18
Send {Blind}{b}{s}
Sleep 98
Send {Blind}{w}
Sleep 25
Send {Blind}{m}
Sleep 247
Send {Blind}{e}{z}
Sleep 24
Send {Blind}{e}
Sleep 105
Send {Blind}{e}
Sleep 133
Send {Blind}{e}{b}
Sleep 56
Send {Blind}{e}
Sleep 15
Send {Blind}{e}
Sleep 115
Send {Blind}{e}{e}{a}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}{d}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}{x}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}{w}
Sleep 104
Send {Blind}{b}
Sleep 17
Send {Blind}{w}
Sleep 101
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 90
Send {Blind}{m}
Sleep 17
Send {Blind}{w}
Sleep 101
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 107
Send {Blind}{q}
Sleep 101
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 90
Send {Blind}{c}
Sleep 17
Send {Blind}{q}
Sleep 101
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 90
Send {Blind}{n}
Sleep 17
Send {Blind}{q}
Sleep 101
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 90
Send {Blind}{a}
Sleep 17
Send {Blind}{q}
Sleep 101
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{j}
Sleep 107
Send {Blind}{j}
Sleep 101
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 90
Send {Blind}{c}
Sleep 17
Send {Blind}{j}
Sleep 101
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 90
Send {Blind}{b}
Sleep 17
Send {Blind}{j}
Sleep 101
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 90
Send {Blind}{m}
Sleep 17
Send {Blind}{j}
Sleep 101
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{h}
Sleep 107
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 90
Send {Blind}{v}
Sleep 17
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 90
Send {Blind}{n}
Sleep 17
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 90
Send {Blind}{a}
Sleep 17
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{g}
Sleep 107
Send {Blind}{g}
Sleep 101
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 90
Send {Blind}{c}
Sleep 17
Send {Blind}{g}
Sleep 101
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 90
Send {Blind}{b}
Sleep 17
Send {Blind}{g}
Sleep 101
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 90
Send {Blind}{a}
Sleep 17
Send {Blind}{g}
Sleep 101
Send {Blind}{g}
Sleep 104
Send {Blind}{g}
Sleep 104
Send {Blind}{h}
Sleep 107
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 90
Send {Blind}{x}
Sleep 17
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 90
Send {Blind}{n}
Sleep 17
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 90
Send {Blind}{a}
Sleep 17
Send {Blind}{h}
Sleep 101
Send {Blind}{h}
Sleep 173
Send {Blind}{h}
Sleep 104
Send {Blind}{h}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 21
Send {Blind}{x}
Sleep 83
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 21
Send {Blind}{b}
Sleep 83
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 21
Send {Blind}{m}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}{b}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}{a}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}{d}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{e}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}{x}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}{b}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}{m}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{w}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}{c}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}{n}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}{a}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{q}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}{c}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}{b}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}{m}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}
Sleep 104
Send {Blind}{j}{j}
Sleep 107
Send {Blind}{h}
Sleep 107
Send {Blind}{h}
Sleep 64
Send {Blind}{h}
Sleep 107
Send {Blind}{h}{v}
Sleep 107
Send {Blind}{h}
Sleep 97
Send {Blind}{h}
Sleep 110
Send {Blind}{h}
Sleep 110
Send {Blind}{h}{n}
Sleep 110
Send {Blind}{h}
Sleep 110
Send {Blind}{h}
Sleep 32
Send {Blind}{h}
Sleep 107
Send {Blind}{h}{a}
Sleep 110
Send {Blind}{h}
Sleep 9
Send {Blind}{h}
Sleep 101
Send {Blind}{h}{h}
Sleep 78
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}{c}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}{b}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}{a}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{g}
Sleep 114
Send {Blind}{h}{h}
Sleep 62
Send {Blind}{h}
Sleep 117
Send {Blind}{h}
Sleep 53
Send {Blind}{h}{h}{v}
Sleep 122
Send {Blind}{h}
Sleep 71
Send {Blind}{h}
Sleep 96
Send {Blind}{h}
Sleep 125
Send {Blind}{h}{n}
Sleep 125
Send {Blind}{h}
Sleep 11
Send {Blind}{h}
Sleep 14
Send {Blind}{h}{h}{a}
Sleep 26
Send {Blind}{h}
Sleep 11
Send {Blind}{h}
Sleep 78
Send {Blind}{h}{h}
Sleep 49
Send {Blind}{j}
Sleep 12
Send {Blind}{j}
Sleep 66
Send {Blind}{j}
Sleep 101
Send {Blind}{j}{x}
Sleep 61
Send {Blind}{j}
Sleep 41
Send {Blind}{j}
Sleep 22
Send {Blind}{j}
Sleep 36
Send {Blind}{j}{b}
Sleep 142
Send {Blind}{j}
Sleep 55
Send {Blind}{j}
Sleep 102
Send {Blind}{j}{j}{j}{m}
Sleep 43
Send {Blind}{j}
Sleep 108
Send {Blind}{q}{d}{b}{z}
Sleep 4596